# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1917, 936)
        MainWindow.setMinimumSize(QtCore.QSize(1917, 936))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: url(:/resources/img.jpeg)")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 340, 161, 71))
        self.pushButton.setStyleSheet("background: transparent")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: transparent")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 190, 151, 41))
        self.pushButton_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 190, 121, 41))
        self.pushButton_3.setStyleSheet("background:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(590, 410, 371, 331))
        self.textBrowser.setStyleSheet("background:rgb(255, 255, 255)")
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 380, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: transparent")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1090, 410, 371, 331))
        self.textBrowser_2.setStyleSheet("background:rgb(255, 255, 255)")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1090, 380, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: transparent")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(830, 750, 131, 21))
        self.pushButton_4.setStyleSheet("background:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1340, 380, 121, 21))
        self.pushButton_5.setStyleSheet("background:rgb(255, 255, 255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1200, 380, 121, 21))
        self.pushButton_6.setStyleSheet("background:rgb(255, 255, 255)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(560, 160, 441, 71))
        self.textBrowser_3.setStyleSheet("background:rgb(255, 255, 255)")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: transparent")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1330, 750, 131, 21))
        self.pushButton_7.setStyleSheet("background:rgb(255, 255, 255)")
        self.pushButton_7.setObjectName("pushButton_7")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(1219, 750, 101, 21))
        self.checkBox.setStyleSheet("background: transparent")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(1159, 750, 51, 21))
        self.checkBox_2.setStyleSheet("background: transparent")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(1600, 690, 221, 41))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(310, 340, 161, 71))
        self.pushButton_8.setStyleSheet("background: transparent")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(110, 460, 161, 71))
        self.pushButton_9.setStyleSheet("background: transparent")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 590, 161, 71))
        self.pushButton_10.setStyleSheet("background: transparent")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(310, 590, 161, 71))
        self.pushButton_11.setStyleSheet("background: transparent")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(310, 460, 161, 71))
        self.pushButton_12.setStyleSheet("background: transparent")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(240, 290, 91, 31))
        self.radioButton.setStyleSheet("background:rgb(255, 255, 255)")
        self.radioButton.setObjectName("radioButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1917, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTimeline = QtWidgets.QMenu(self.menubar)
        self.menuTimeline.setObjectName("menuTimeline")
        self.menuSlots = QtWidgets.QMenu(self.menubar)
        self.menuSlots.setObjectName("menuSlots")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Different_Timeline = QtWidgets.QAction(MainWindow)
        self.actionImport_Different_Timeline.setObjectName("actionImport_Different_Timeline")
        self.actionExport_Current_Timeline = QtWidgets.QAction(MainWindow)
        self.actionExport_Current_Timeline.setObjectName("actionExport_Current_Timeline")
        self.actionToggle_Slot = QtWidgets.QAction(MainWindow)
        self.actionToggle_Slot.setObjectName("actionToggle_Slot")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuTimeline.addAction(self.actionImport_Different_Timeline)
        self.menuTimeline.addAction(self.actionExport_Current_Timeline)
        self.menuSlots.addAction(self.actionToggle_Slot)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTimeline.menuAction())
        self.menubar.addAction(self.menuSlots.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Last ping:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">?</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Connectivity Settings"))
        self.pushButton_3.setText(_translate("MainWindow", "Try Ping"))
        self.label_3.setText(_translate("MainWindow", "Clips:"))
        self.label_4.setText(_translate("MainWindow", "Timeline:"))
        self.pushButton_4.setText(_translate("MainWindow", "Add to Timeline"))
        self.pushButton_5.setText(_translate("MainWindow", "Export Timeline"))
        self.pushButton_6.setText(_translate("MainWindow", "Import Timeline"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Output:</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Remove from Timeline"))
        self.checkBox.setText(_translate("MainWindow", "Stop at each clip"))
        self.checkBox_2.setText(_translate("MainWindow", "Loop"))
        self.radioButton.setText(_translate("MainWindow", "Timeline Mode"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTimeline.setTitle(_translate("MainWindow", "Timeline"))
        self.menuSlots.setTitle(_translate("MainWindow", "Slots"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionImport_Different_Timeline.setText(_translate("MainWindow", "Import Different Timeline"))
        self.actionExport_Current_Timeline.setText(_translate("MainWindow", "Export Current Timeline"))
        self.actionToggle_Slot.setText(_translate("MainWindow", "Toggle Slot"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


import background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
