import socket
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import json
import time

timerInterval = 100
mainOutput = ""

def outputToMain(arg):
    global mainOutput
    mainOutput = arg

def TCPSEND(MESSAGE):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.connect((fileRetrive("tcpIP"), int(fileRetrive("tcpPORT"))))
        s.send(MESSAGE)
        data = s.recv(1024)
        return data
        s.close()
    except:
        return "Failed to connect to server with IP %s and Port %s !" % (fileRetrive("tcpIP"), int(fileRetrive("tcpPORT")))

def fileRetrive(arg):
    with open("configFile.json", "r") as f:
        return json.load(f)[arg]

def fileSet(arg, setting):
    with open("configFile.json", "r+") as f:
                data = json.load(f)
                data[arg] = setting
                f.seek(0)
                json.dump(data, f)
                f.truncate()

def ping():
    global lastPing
    response = TCPSEND("ping")
    if response == "200":
        lastPing = "Sucessfull"
    else:
        lastPing = "Unsucessfull :("


def showConnSettings():
    Dialog.show()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(90, 20, 201, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(90, 50, 201, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(90, 90, 51, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.actionsUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kayto - Connection Settings"))
        self.comboBox.setItemText(0, _translate("Dialog", "Blackmagic Hyperdeck Studio Mini "))
        self.label.setText(_translate("Dialog", "Device Type:"))
        self.label_2.setText(_translate("Dialog", "IP Address:"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "%s" % fileRetrive("tcpIP")))
        self.label_3.setText(_translate("Dialog", "TCP Port:"))
        self.plainTextEdit_2.setPlainText(_translate("Dialog", "%s" % fileRetrive("tcpPORT")))
        self.pushButton.setText(_translate("Dialog", "Apply"))

    def actionsUi(self, Dialog):
        self.pushButton.clicked.connect(lambda: self.updateFile(Dialog))

    def updateFile(self, Dialog):
        fileSet("tcpIP", self.plainTextEdit.toPlainText())
        fileSet("tcpPORT", self.plainTextEdit_2.toPlainText())


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 750)
        MainWindow.setWindowOpacity(6.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timer = QtCore.QTimer()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 130, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 40, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 103, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 370, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(370, 370, 160, 22))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 370, 256, 192))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 340, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(580, 370, 51, 16))
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 300, 81, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 540, 121, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(630, 370, 101, 16))
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 570, 121, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 570, 121, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(290, 430, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(290, 160, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(290, 190, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(750, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(830, 130, 91, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(830, 160, 91, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(750, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(760, 360, 431, 311))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(760, 330, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(60, 100, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(370, 400, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(450, 400, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(340, 480, 160, 22))
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setProperty("value", 50)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(306, 480, 31, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(510, 480, 31, 21))
        self.label_9.setObjectName("label_9")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 460, 261, 61))
        self.groupBox.setObjectName("groupBox")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(510, 240, 31, 21))
        self.label_10.setObjectName("label_10")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(340, 240, 160, 22))
        self.horizontalSlider_4.setMaximum(100)
        self.horizontalSlider_4.setProperty("value", 50)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(306, 240, 31, 21))
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 220, 261, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(970, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(1050, 130, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(540, 370, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(370, 130, 160, 22))
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 50)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(580, 130, 51, 16))
        self.checkBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(290, 130, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(540, 130, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(630, 130, 101, 16))
        self.checkBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(190, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(260, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(970, 160, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(1050, 160, 75, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(470, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(360, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(890, 0, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.actionsUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kayto"))
        self.label.setText(_translate("MainWindow", "Last ping:"))
        self.label_2.setText(_translate("MainWindow", "Placeholder"))
        self.pushButton.setText(_translate("MainWindow", "Connection Settings"))
        self.pushButton_2.setText(_translate("MainWindow", "Ping"))
        self.label_3.setText(_translate("MainWindow", "Clips:"))
        self.pushButton_3.setText(_translate("MainWindow", "Play"))
        self.label_4.setText(_translate("MainWindow", "Timeline:"))
        self.checkBox.setText(_translate("MainWindow", "Loop"))
        self.pushButton_4.setText(_translate("MainWindow", "Add to Timeline"))
        self.pushButton_5.setText(_translate("MainWindow", "Remove from Timeline"))
        self.checkBox_2.setText(_translate("MainWindow", "Stop at each clip"))
        self.pushButton_6.setText(_translate("MainWindow", "Export Timeline"))
        self.pushButton_7.setText(_translate("MainWindow", "Import Timeline"))
        self.pushButton_9.setText(_translate("MainWindow", "Stop"))
        self.pushButton_10.setText(_translate("MainWindow", "Record"))
        self.pushButton_11.setText(_translate("MainWindow", "Stop"))
        self.pushButton_12.setText(_translate("MainWindow", "Record"))
        self.label_5.setText(_translate("MainWindow", "Video Input:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Component"))
        self.comboBox.setItemText(1, _translate("MainWindow", "SDI"))
        self.comboBox.setItemText(2, _translate("MainWindow", "HDMI"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Embedded"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "XLR"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "RCA"))
        self.label_6.setText(_translate("MainWindow", "Audio Input:"))
        self.label_7.setText(_translate("MainWindow", "Output:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Slot 1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Slot 2"))
        self.pushButton_13.setText(_translate("MainWindow", "Prev Clip"))
        self.pushButton_14.setText(_translate("MainWindow", "Next Clip"))
        self.label_8.setText(_translate("MainWindow", "Back"))
        self.label_9.setText(_translate("MainWindow", "Front"))
        self.groupBox.setTitle(_translate("MainWindow", "Shuttle"))
        self.label_10.setText(_translate("MainWindow", "Front"))
        self.label_11.setText(_translate("MainWindow", "Back"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Shuttle"))
        self.label_12.setText(_translate("MainWindow", "Formatar:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Slot 1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Slot 2"))
        self.pushButton_15.setText(_translate("MainWindow", "Reset"))
        self.checkBox_3.setText(_translate("MainWindow", "Loop"))
        self.pushButton_8.setText(_translate("MainWindow", "Play"))
        self.pushButton_16.setText(_translate("MainWindow", "Reset"))
        self.checkBox_4.setText(_translate("MainWindow", "Stop at each clip"))
        self.label_13.setText(_translate("MainWindow", "Uptime:"))
        self.label_14.setText(_translate("MainWindow", "Placeholder"))
        self.pushButton_17.setText(_translate("MainWindow", "Prepare"))
        self.pushButton_18.setText(_translate("MainWindow", "Confirm"))
        self.label_15.setText(_translate("MainWindow", "Placeholder"))
        self.label_16.setText(_translate("MainWindow", "Device Info:"))
        self.label_17.setText(_translate("MainWindow", "Kayto - Blackmagic Ethernet Control Protocol GUI Wrapper"))

    def actionsUi(self, MainWindow):
        self.pushButton.clicked.connect(showConnSettings)
        self.pushButton_2.clicked.connect(ping)
        self.timer.timeout.connect(lambda: self.updateWindow(MainWindow))
        self.timer.start(timerInterval)
    def updateWindow(self, MainWindow):
        global mainOutput
        global lastPing
        if mainOutput != "":
            self.textBrowser.append(mainOutput)
            mainOutput = ""
        #self.label_2.setText(lastPing)

if __name__ == "__main__":
    print("Starting Kayto...")
    #ping()
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
